### PR TITLE
Changed the Session.single to throw an exception if the query returns more than one row

### PR DESCRIPTION
**Pull request by bonkowski**
I realize this may create problems for existing code that relies on that you do not get an exception in these cases.

### CODE REVIEW

**Comment by seratch** [comment]
Thanks for taking the time to make this pull request!

I would like to avoid changing the default behavior. Can you add `strict` flag to session object constructor (default: false)?

* https://github.com/seratch/kotliquery/blob/1.3.1/src/main/kotlin/kotliquery/package.kt#L20-L31
* https://github.com/seratch/kotliquery/blob/1.3.1/src/main/kotlin/kotliquery/Session.kt#L18-L22

Also, having unit tests for the change would be appreciated.

**Comment by bonkowski** [comment]
Absolutely, I like your proposal👍

**Comment by seratch** [comment]
Thanks for updating! Looks great to me 👍

**Comment by seratch** [comment]
Your change is included in the latest version (v1.6.0)

**Pull request merged**
