### PR TITLE
UUID fix

### PR DESCRIPTION
**Pull request by ievgen-kapinos**
Fix for issue reported by @busches
https://github.com/seratch/kotliquery/pull/49#issuecomment-1049932169

### CODE REVIEW

**Comment by ievgen-kapinos** [comment]
Hi @seratch!
Can you take a look?

**Comment by busches** [comment]
Shouldn't this have some kind of test to prevent it happening again?

**Comment by ievgen-kapinos** [comment]
We have test for uuid which uses H2 DB. The problem, this DB accepts string representation for uuid type. But this is not the case for postgres. The only solution is to run tests over all supported DBs. But that requires: a lot of effort, test redesign and probably tuning CI (e.g. if run postgres, MySQL etc in docker )

That is way more work for simple hot fix (revert change) I can offer.

**Comment by seratch** [comment]
Thanks for the fix! I'll release a new patch version shortly.

As for the better testing topic, I've been doing better in scalikejdbc (Scala database library): https://github.com/scalikejdbc/scalikejdbc/blob/master/.github/workflows/ci.yml If someone is interested in working on a similar solution in kotliquery project, I'm happy to be a reviewer of the change.

**Comment by ievgen-kapinos** [comment]
@seratch Thanks for quick release!

**Comment by busches** [comment]
Confirmed this is back to working as expected, thanks!

**Pull request merged**
