### PR TITLE
issue 27, sql array

### PR DESCRIPTION
**Pull request by rubendm92**
Related to what we talked here https://github.com/seratch/kotliquery/issues/27

I've added a `createArrayOf` method in the Session class. Kinda ugly, but at least we hide implementation details.

I've also added an `array` method in Row, in order to retrieve a Kotlin array instead of a sql array. I'm not really sure if I did the right thing with the `inline fun` since I'm kinda new to Kotlin, but I didn't find other way to implement it. Let me know if there is a better way :)

### CODE REVIEW

**Comment by seratch** [comment]
LGTM, thanks.

**Comment by rubendm92** [comment]
Great! When are you planning to do a new release?

**Comment by seratch** [comment]
will do today, JST

**Comment by seratch** [comment]
released https://oss.sonatype.org/content/repositories/releases/com/github/seratch/kotliquery/1.3.0/

**Pull request merged**
